sudo: required
dist: trusty

language: php

php:
    - 7.2

env:
    - NODE_VERSION="8.14.1"

services:
    - mysql

before_install:
    - nvm install $NODE_VERSION
    - node --version
    - yarn --version

script:
    - make test


cache:
    yarn: true
    directories:
        - $HOME/.composer/cache
